### ISSUE TITLE
Extending custom validations

### ISSUE THREAD

**Issue by Sult** [playpauseandstop/rororo#100]
Hello,

I cant seem to figure out how to extend Validations with custom validations.
Whenever I raise something, i (default?) error.

Example (for someplicity)
```
@operations.register
async def register_user(request: web.Request) -> web.Response:
    with openapi_context(request) as context:
        # something in context fails on more detailed validation
        raise ValidationError.from_request_errors([OpenAPIParameterError("Something is wrong"), ], base_loc=["fieldname"])
```

I end up with this error:
`{"detail": [{"loc": ["response", 0], "message": "'detail' is not of type object"}]}`

I assume that whenever i use `with openapi_context(request) as context:` i get into the reponse layer.
Sadly i cant figure out how to combine it with my extra validations

**Comment by playpauseandstop** [comment]
Hi,

There is a `ValidationError.from_dict` class method, which is designed to simplify supplying custom validation errors for end user.

```python
async def add_comment(request: web.Request) -> web.Response:
    """Add comment, but only if text do not contain stop words"""
    # Get validated data from request, this is a shortcut to,
    #
    # .. code-block:: python
    #
    #     context = get_openapi_context(request)
    #     data = context.data 
    #
    # In that moment request data **already** validated via OpenAPI Schema
    data = get_validated_data(request)
    
    # Now call custom validator to check whether comment text contains stop words
    if has_stop_words(data["text"]):
        # If text contain stop words - do not allow user add a comment
        raise ValidationError.from_dict(body={"text": "Please use kind language"})

    ...
```

I just updated docs to contain at least [ValidationError API docs](https://rororo.readthedocs.io/en/latest/api.html#rororo.openapi.exceptions.ValidationError) and will provide more docs & examples later.

----

As of `openapi_context`, this is just a syntax sugar for getting valid request data, you can use it as context manager, but if you don't prefer extra indent layer, you can use `get_openapi_context` function instead.

----

Hope you find my answers helpful, if not I will be happy to provide more information on the topic.

**Comment by Sult** [comment]
Thanks a lot!.
nice package btw 👍
