### ISSUE TITLE
Registering operations from an aiohttp.web.View class

### ISSUE THREAD

**Issue by hiboo** [playpauseandstop/rororo#45]
Hello there !

I was wondering if there are ways to register operations from an `aiohttp.web.View` class instead of doing it method by method?

For example I would like to do something like:
```python
from aiohttp import web
from rororo import OperationTableDef

operations = OperationTableDef()

# @operations.register ?
class LogCollectionView(web.View):
    # @operations.register("log_collection_get") ?
    async def get(self):
        pass

    # @operations.register("log_collection_post") ?
    async def post(self):
        pass
```

Thank you in advance!

>Using rororo 2.0.0b3

**Comment by playpauseandstop** [comment]
Hi @hiboo 

Thanks for your question. 

Looks like I've completely forgot about `web.View` presence and missed to ensure support of decorating view methods. 

I'll work on MR soon and will include this into next `2.0.0rc0` release, which I planned to release at PyPI soon.

**Comment by hiboo** [comment]
Awesome! Thank you very much ;)

**Comment by playpauseandstop** [comment]
@hiboo 

One question about implementation details. As of now I see two options on how `web.View` support should be added to the `rororo`,

1. Explicit one. Just decorate every method handler with `@operations.register` and expect everything will work fine, e.g.,

   ```python
   class UserView(web.View):

       @operations.register("retrieve_profile")
       async def get(self) -> web.Response:
           ...

       @operations.register("update_profile")
       async def put(self) -> web.Response:
           ...
   ```

2. But sometimes it might be very annoying to decorate all `web.View` method handlers, and there should be a way to decorate a whole `web.View` class with `@operations.register`. But here is a problem: `operationId` should be a unique value in OpenAPI 3 schema, which means you cannot do,

    ```python
    @operations.register
    class UserView(web.View):
        ...
    ```

    and in same time share `UserView` as `operationId` in the schema. With that in mind I see three options there,

    1. Provide special `@operations.register_path` helper, which will register all possible method handlers in view by its name. In that case, it will not have any connection with `operationId`, but you will need to provide route path several times (once, for `@operations.register_path("/api/me")` call, then for `@routes.view("/api/me")` or `web.view("/api/men")`)
    2. Allow to decorate with simple `@operations.register` call

**Comment by hiboo** [comment]
Thanks for all those thoughts!
First of all, I think that, in a first time, the best approach is to let dev decorate each functions of the view manually  (your case 1.)

This way you ensure compatibility with web.View and you let full control on operation ID.

Then we could think about adding another decorator or whatever to « simplify » this by shortcuting (your point 2.) What could be interesting is to generate automatically the operation ID for each function of the view by concatenating à base name (the view name for example) with the method name. However I’m not sure I know enough your library to understand what this would imply.

I’m writing this from my phone so I’m sorry to not provide a bit of example for demonstrating my thoughts. I’ll try to Enhance my answer on Monday if you want me to

**Comment by playpauseandstop** [comment]
Hi @hiboo,

I've played a bit with class based views support for the `rororo` over the weekend and looks like I'll need to provide more changes to its core. However, as of now, I plan to support class based views as follows,

1. Default. OpenAPI `operationId` matches `ViewMethod.__qualname__`, for example,

   ```yaml
   paths:
     "/todos":
       post:
         operationId: "TodosView.post"
       get:
         operationId: "TodosView.get"
       delete:
         operationId: "TodosView.delete"
   ```

   ```python
   @operations.register
   class TodosView(web.View):
       async def post(self) -> web.Response:
           ...

       async def get(self) -> web.Response:
           ...

       async def delete(self) -> web.Response:
           ...
   ```

2. Alias for view class. Usable, when you don't want to use `View.__qualname__` in your `operationId`,


   ```yaml
   paths:
     "/todos":
       post:
         operationId: "todos.post"
       get:
         operationId: "todos.get"
       delete:
         operationId: "todos.delete"
   ```
   
   ```python
   @operations.register("todos")
   class TodosView(web.View):
       ...
   ```

3. Setup mapping between `ViewMethod` & `operationId` to use. Usable, when you don't want to name operations awkwardly in your schema,

   ```yaml
   paths:
     "/todos":
       post:
         operationId: "create_todo"
       get:
         operationId: "list_todos"
       delete:
         operationId: "delete_todos"
   ```

   ```python
   @operations.register
   class UserView(web.View):
       @operations.register("create_todo")
       async def post(self) -> web.Response:
           ...

       @operations.register("list_todos")
       async def get(self) -> web.Response:
           ...

       @operations.register("delete_todos")
       async def delete(self) -> web.Response:
           ...
   ```

As you might see, the latest design require developer to decorate `web.View` instead of `ViewMethod`. This is necessary as `rororo` need to add the view to [`web.RouteTableDef`](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.RouteTableDef) via `routes.view(...)` call, not via `routes.route(...)` as done for other handlers.

In any case, I'll continue implement the feature and hope to have first draft soon. For better understanding for end users, I decided to implement [Todo-Backend](http://todobackend.com) with class based views. 

Will keep you posted, thanks!

**Comment by hiboo** [comment]
Sounds perfect to me!

Thanks a lot for your work and reactivity ;)

**Comment by playpauseandstop** [comment]
@hiboo 

#49 introducing basic class based views support for `rororo`. 

With that in mind, I expect to have `2.0.0rc0` released around Fri-Sat, as I still need to support last case of using custom `operationId` for view method as,

```python
@operations.register
class TodosView(web.View):
    @operations.register("create_todo")
    async def get(self) -> web.Response:
        ...
```

----

But. [Todo-Backend](https://github.com/playpauseandstop/rororo/tree/master/examples/todobackend/views.py) implementation now using class based views. Hope you have it helpful

**Comment by playpauseandstop** [comment]
Hi @hiboo,

I've just merged full class based views support to `rororo@master` branch. I will spend tomorrow to integrate latest `rororo` within all my projects, and if everything went fine, I'll do the `2.0.0rc0` release as soon as possible.

Also, after `2.0.0rc0` I don't see many features left in a tank for final `2.0.0` release, so hopefully to have it in a week or so.

Thanks again for your request, it would be a disaster to release `2.0.0` version without class based views support, but now it wouldn't 😄

**Comment by playpauseandstop** [comment]
Hi @hiboo,

[2.0.0rc0](https://github.com/playpauseandstop/rororo/releases/tag/v2.0.0rc0) released. Feel free to install it from [PyPI](https://pypi.org/project/rororo/2.0.0rc0/).

Thanks
