### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/rororo#7]
Need to provide examples of using schemas and other `rororo` gotchas. I think the most easiest way is porting [swapi](https://github.com/phalt/swapi) (or at least some its part) to `aiohttp.web` & `rororo.schemas`.

**Comment by cdnsteve** [comment]
The `README.rst` link to On Read the Docs link is broken FYI:
http://rororo.readthedocs.org/

**Comment by playpauseandstop** [comment]
@cdnsteve 

Unfortunatelly docs now is not present for `rororo` package. Hopefully I'll provide them soon, as now it last part before publishing `1.0.0` release.

Few examples can be found in `tests`, but that's completely not optimal way to share my vision of using `rororo` in real world.

**Comment by playpauseandstop** [comment]
`rororo.schemas` is now a history :(
