### ISSUE TITLE
optimize setup_openapi

### ISSUE THREAD

**Issue by chobeat** [playpauseandstop/rororo#84]
**Problem:** Using rororo with aiohttp, I end up reloading the openapi.yaml for every test and populating the app with setup_openapi. This takes up 30% of the total time of my test suite. 15% is just loading the file in read_schema, while another 12% is spent in create_spec. 

**Proposal:** decouple the spec creation from the addition of fields and routes to the app. After this, create a separate setup_openapi (maybe called setup_test_openapi) that can take a `Spec` object as an additional parameter and set it instead of creating it. The underlying implementation will be the same, but the first half of the current setup_openapi will be optional

I can try to work on this if you don't see conflicts arising

**Comment by playpauseandstop** [comment]
Hi @chobeat 

Thanks for your question, I’m curious whether this trick helps you: https://rororo.readthedocs.io/en/latest/openapi_speedups.html#testing-cache-reading-schema-and-spec-creation

Here the example in rororo test suite: https://github.com/playpauseandstop/rororo/blob/4e32b4a0b230c713645205fd63d37a919859a9a8/tests/test_openapi_openapi.py#L43

In my projects passing `cache_create_schema_and_spec=True` helps save around 40-45% on running tests

**Comment by playpauseandstop** [comment]
As of initial proposal of passing spec instance directly in `setup_openapi` I also thought about that many times, so maybe I will need to implement that option as well

Thanks again for starting discussion about the topic

**Comment by chobeat** [comment]
Oh, it looks totally fine. I was using an older version of rororo and I must have missed that parameter. I will try it for sure, thanks.

**Comment by playpauseandstop** [comment]
Great!

But I believe directly passing `Spec` instance to `setup_openapi` function instead of `Path` is completely valid usecase

And shouldn’t take long to implement and test

**Comment by chobeat** [comment]
I tried your suggestion: it goes faster but I think I've found an unrelated bug. In `unmarshallers.py:198` it tries to access the keys of a None. From what I understand, it's doing recursion on nested dicts but it tries on the None value and it fails. This has been introduced between 2.0.0b3 and 2.0.0rc2. Before it was working properly. 

I think it's happening on all my responses that contain at least a None value somewhere.

**Comment by playpauseandstop** [comment]
Hi @chobeat,

Your initial proposal on passing `spec` into `setup_openapi` call fulfilled in https://github.com/playpauseandstop/rororo/pull/86

After it will be merged into `master`, you'll be able to,

```py
from pathlib import Path

import yaml
from aiohttp import web
from openapi_core.shortcuts import create_spec
from rororo import setup_openapi


openapi_yaml = Path(__file__).parent / "openapi.yaml"
schema = yaml.load(
    openapi_yaml.read_bytes(), Loader=yaml.CSafeLoader
)
spec = create_spec(schema)

app = setup_openapi(
    web.Application(), 
    operations,
    schema=schema,
    spec=spec,
)
```

Also, in contradiction, with your initial request, you must pass `schema` dict to `setup_openapi` as well, as *rororo* internally needs to access raw schema for,

- Handing OpenAPI schema via `GET /api/openapi.yaml` or `GET /api/openapi.json`
- Deciding which server to use by iterating over `servers` list
